def clean_latex_output(latex_str):
    latex_to_symbol = {
        r'\times': '×',
        r'\cdot':'×',
        r'\text{': '',  
        r'}': '',       
        r'\frac{': '',  
        r'}{': '/',     
        r'{': '/',      
        r'//':'/',
        r'\approx': '≈',
        r'\text': '',   
        r'\\': '\n',    
        r'\[': '',
        r'/{':'/',
        r'\]':'',
        r'**':'',
        r'\)':')',
        r'\(':'(',
        r'\,': '/',
        r'\leq':'≤',
        r'\geq':"≥",
        r'\sqrt':'√',
        r'\quad':' ',
        r'\Rightarrow':'→',
        r'\implies':'⇒',
        r'\tag': '-@ ',
        r'\boxed': '',
        r'*':'',
        r'#':'',
        r'\right':"",
        r'\left':'',
        r'( /':'',
        r' )':'',
        r'\\( ':'',
        r'( ':'',
        r'√/':'√',
        f'\n/':'',
        r'  /': ' ',
        r'-@ /': '-@',
        r'≈ /':'≈',
        r'\begin':'',
        r'\end':'',
        r'/align':'',
        r' &  ':'',
        r' \$' :'$',
        r'\pm':'±',
        r'\pi':'π',
        r'^/':'^',
        r'_/':'_',
        r'\tan':'tan',
        r'^\circ':'°',
        r'\theta':'θ',
        r' / ':'',
        r'\mathbf/':'',
        r'arrow':'→'
    }

    for latex, symbol in latex_to_symbol.items():
        latex_str = latex_str.replace(latex, symbol)
  
    return latex_str